name: Flutter build apk CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: install dependencies
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2

    - name: Flutter action
      uses: subosito/flutter-action@v1.3.0
      with: 
        flutter-version: 'v1.12.13+hotfix.9'
    - run: flutter pub get
    - run: flutter analyze
    - run: flutter test
    - run: flutter drive --target=test_driver/app.dart
    - run: flutter build apk
